name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

env:
  # Define o nome da imagem baseada no repositÃ³rio (ex: ghcr.io/seu-usuario/seu-repo)
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout do codigo
        uses: actions/checkout@v4

      - name: configurar python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: rodar testes (pytest)
        run: |
          pytest -v

      - name: login no github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: converter nome da imagem para minusculas
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> $GITHUB_ENV

      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}